apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $(NAMESPACES_APPLICATIONS)

resources:
  - service.yaml
  - endpoints.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: homeassistant
      app.kubernetes.io/part-of: homeassistant
