apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: $(NAMESPACES_APPLICATIONS)
spec:
  type: ClusterIP
  ports:
    - name: http
      port: $(PORTS_HOMEASSISTANT)
      targetPort: $(PORTS_HOMEASSISTANT)
  # NO selector (important)
