apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: bijouxlabs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123      # service port inside k8s
      targetPort: 8123
  # NO selector (important)
