apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: bijouxlabs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: $(PORT_HOMEASSISTANT)
      targetPort: $(PORT_HOMEASSISTANT)
  # NO selector (important)
