apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip-config
  namespace: kube-system
data:
  vip: "192.168.0.220"
  vip_interface: "ens18"
  address: "0.0.0.0"
  port: "6443"
  cp_enable: "true"
  lb_enable: "false"
  vip_arp: "true"
  leaderElection: "true"
