apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $(NAMESPACES_APPLICATIONS)
resources:
  - configmap.yaml
  - pvc-uploads.yaml
  - deployment.yaml
  - service.yaml
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: tauc-speedtest
      app.kubernetes.io/part-of: tauc-speedtest
