apiVersion: v1
kind: Service
metadata:
  name: tauc-speedtest
  namespace: $(NAMESPACES_APPLICATIONS)
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  type: LoadBalancer
  loadBalancerIP: $(LB_IP_TAUCSPEEDTEST)     # pick a free IP from your MetalLB pool
  selector:
    app: tauc-speedtest
  ports:
    - name: http-8089
      port: 8089
      targetPort: $(PORT_TAUCSPEEDTEST)
      protocol: TCP
