apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opengist
  namespace: $(NAMESPACES_APPLICATIONS)
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: $(TLS_CERT_RESOLVER)
    traefik.ingress.kubernetes.io/router.middlewares: bijouxlabs-allow-ha-lan@kubernetescrd
spec:
  ingressClassName: $(TLS_INGRESS_CLASS)
  rules:
  - host: $(DOMAIN_OPENGIST)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opengist
            port:
              number: $(PORT_OPENGIST)
  tls:
  - hosts: [$(DOMAIN_OPENGIST)]