apiVersion: v1
kind: Service
metadata:
  name: opengist
  annotations:
    # Optional: pin a MetalLB address you reserved
    metallb.universe.tf/loadBalancerIPs: "192.168.0.162"
spec:
  type: LoadBalancer
  selector:
    app: opengist
  ports:
    - name: http
      port: 6157
      targetPort: 6157
