apiVersion: v1
kind: Service
metadata:
  name: opengist
  annotations:
    metallb.universe.tf/loadBalancerIPs: "$(LB_IP_OPENGIST)"
spec:
  type: LoadBalancer
  selector:
    app: opengist
  ports:
    - name: http
      port: 6157
      targetPort: 6157
