apiVersion: v1
kind: Service
metadata:
  name: iperf3
  namespace: bijouxlabs
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.160
  selector:
    app: iperf3
  ports:
    - name: tcp-iperf
      port: 5201
      protocol: TCP
      targetPort: 5201
    - name: udp-iperf
      port: 5201
      protocol: UDP
      targetPort: 5201
