apiVersion: v1
kind: Service
metadata:
  name: iperf3
  namespace: $(NAMESPACES_APPLICATIONS)
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  type: LoadBalancer
  loadBalancerIP: $(LB_IP_IPERF3)
  selector:
    app: iperf3
  ports:
    - name: tcp-iperf
      port: $(PORT_IPERF3)
      protocol: TCP
      targetPort: $(PORT_IPERF3)
    - name: udp-iperf
      port: $(PORT_IPERF3)
      protocol: UDP
      targetPort: $(PORT_IPERF3)
