apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:NZC5q2Qdc4lIH2C+DJaxSl3CoWwJq4M5Rmq8FcfZcqqEh0llDko4NQ==,iv:WoHpiXZJFWygK3xxgoiPItlsQyeEa28/Xi93HA3hgZg=,tag:KHJPmXuCj+19ViZeXsMu8A==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:CekBMAXpzOeGV9n5pIk3aGiuJAatDAQ=,iv:hEPIAQRd5E4t8qeBf/MtY85Obv+XCTpa3aHuVKTI50g=,tag:fi8mB+Q8TPftmdAyXvuFVA==,type:str]
sops:
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcTZ5NU1LL1cxWGZ3b01a
            WUdiVERobkR2aFc1bDYrM2dRYlNOWXFLYmljCkZPZWxkSDdZcUl0M0hkMHFKRmVQ
            YWZVdllYN0JGbEkvSDhXMXY5SmltazgKLS0tIFl0MXZpNVNBby9PMHBHcGk0Y0ds
            TGFqMXAraXRmOWJ2a3R1Yk5qdVF4VWMKpzU95Of1ronsWNvhUvcGz96VOMa+5fXa
            7AMfJi/QzcLqobVg0QYw67q8/E1BFWX97799Nd9jzMnRG2Y63hp70Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T14:27:40Z"
    mac: ENC[AES256_GCM,data:F1l3kqJ0qZG538e8hTsRIuc5xtRJWcBRwCsHROXV2BJ1KnsFmxD24EgUrYFVs4BdjxXPCZu/O7FOE1SEVrdf354ez8aJA8Diz75FxtLZge6dWBhVn4D2jr+Jl0CBYD3Fz8JNQ7LnDBtoYGneJhSlwsPMuELMuj+b6hyvWFOYUCw=,iv:QTOTy5zyxiOj+wBFs8MDJGvf1RJ4KC/KNNIbJcdGqkM=,tag:0PhoOG+0FJdJCeeGQqXijw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
