---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bijouxlabs
resources:
  - claim.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: homeassistant
      app.kubernetes.io/part-of: homeassistant