apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netdata
  namespace: bijouxlabs
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # if you wired the Cloudflare DNS-01 certResolver as "cloudflare"
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  ingressClassName: $(TLS_INGRESS_CLASS)
  rules:
  - host: $(DOMAIN_NETDATA)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netdata
            port:
              number: $(PORT_NETDATA)
  # tls:
  # - hosts:
  #   - netdata.bijouxlabs.cc

