apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bijouxlabs
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - stream-config.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: netdata
