apiVersion: v1
kind: Service
metadata:
  name: netdata
  namespace: bijouxlabs
  labels: { app: netdata }
spec:
  type: LoadBalancer
  selector:
    app: netdata
  ports:
    - name: http
      port: $(PORT_NETDATA)
      targetPort: $(PORT_NETDATA)
      protocol: TCP
