apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-stream
  namespace: bijouxlabs
data:
  stream.conf: |
    [stream]
      enabled = yes
      default port = 19999
      mode = parent
      allow from = *

    # node01m910
    [b5e18454-819c-4882-9cdf-e996ea526d73]
      enabled = yes
      default memory mode = dbengine
      health enabled by default = auto

    # node02m910
    [b0f2047d-6321-42f1-b4da-29b7ef0e4455]
      enabled = yes
      default memory mode = dbengine
      health enabled by default = auto

    # node03m920
    [823195ab-7314-44f0-af56-d40a3b216ec1]
      enabled = yes
      default memory mode = dbengine
      health enabled by default = auto

    # node04g800
    [f6c9b152-b716-4a30-9a83-e9bab7dd4dff]
      enabled = yes
      default memory mode = dbengine
      health enabled by default = auto
      
    # proxmox
    [30bc80dc-7cf5-4a8e-b915-53faf2802072]
      enabled = yes
      default memory mode = dbengine
      health enabled by default = auto


